---
server:
  port: 8084

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: business-service
        uri: lb://business-service
        predicates:
        - Path=/businesses/**
        filters:
        - RewritePath=/businesses/(?<path>.*), businesses/$\{path}
      - id: reactive-business-service
        uri: lb://reactive-business-service
        predicates:
        - Path=/reactive-business/**
        filters:
        - RewritePath=/reactive-business/(?<path>.*), /$\{path}
