---
server:
  port: 8084

security:
  oauth2:
    resource: 
      service-id: oauth2id
    client:
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 10000

spring:
  data:
    mongodb:
      uri: mongodb://sakksoftware:sakk11software@ds137651.mlab.com:37651/bb-gateway-service
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: business-service
        uri: lb://business-service
        predicates:
        - Path=/businesses/**
        filters:
        - RewritePath=/businesses/(?<path>.*), /$\{path}
#     - id: reactive-business-service
#        uri: lb://reactive-business-service
#        predicates:
#        - Path=/reactive-business/**
#        filters:
#        - RewritePath=/reactive-business/(?<path>.*), /$\{path}

