---
server:
  port: 8084

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: business-service
        uri: lb://business-service
        predicates:
        - Path=/business**
        filters:
        - RewritePath=/business/(?<path>.*), /$\{path}
      - id: reactive-business-service
        uri: lb://reactive-business-service
        predicates:
        - Path=/reactive-business**
        filters:
        - RewritePath=/business/(?<path>.*), /$\{path}
